const state={route:"/",builderPrompt:"",generating:false,projects:[
{name:"Urban Fitness",domain:"urbanfitness.demo",plan:"Business",visitors:"12,480"},
{name:"Velora Restaurant",domain:"velora.demo",plan:"Premium",visitors:"8,921"},
{name:"Nova Realty",domain:"novarealty.demo",plan:"Starter",visitors:"4,306"},
{name:"PixelCraft Agency",domain:"pixelcraft.demo",plan:"Business",visitors:"7,184"}]};

const templates=[
["Maison Noir","Restaurant","Premium"],["Aurelia","Salon","Premium"],["Iron District","Gym","Premium"],["Northline","Real Estate","Premium"],
["Luma Stay","Hotel","Premium"],["Studio Eight","Portfolio","Premium"],["Arc & Co.","Agency","Premium"],["Orbit Labs","Startup","Premium"]
];

function toast(msg){const el=document.querySelector("#toast");el.textContent=msg;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2400)}
function app(){document.querySelector("#appView").innerHTML=router();bind();window.scrollTo(0,0)}
function router(){const r=location.hash.slice(1)||"/";state.route=r;
if(r==="/")return home(); if(r==="/builder")return builder(); if(r==="/templates")return templatesPage(); if(r==="/pricing")return pricing();
if(r==="/how")return how(); if(r==="/login")return auth("Welcome back","Log in to your Velora workspace"); if(r==="/signup")return auth("Create your workspace","Start building your first premium website");
if(r==="/forgot-password")return auth("Reset your password","We'll send a secure reset link"); if(r==="/dashboard")return dashboard("Overview");
if(r==="/dashboard/websites")return dashboard("My Websites"); if(r==="/dashboard/domains")return dashboard("Domains");
if(r==="/dashboard/analytics")return dashboard("Analytics"); if(r==="/dashboard/billing")return dashboard("Billing");
if(r==="/dashboard/settings")return dashboard("Settings"); if(r==="/admin")return admin();
if(r.startsWith("/website/"))return websiteDetail(); return home()}

function home(){return `<div class="container"><section class="hero"><div><span class="eyebrow">AI WEBSITE STUDIO · RENTAL PLATFORM</span><h1>Build premium websites with <em>AI.</em><br>Rent them. Grow.</h1><p>Describe your idea. Velora designs, builds, optimizes and launches a professional website in minutes — then keeps it hosted for you.</p><div class="hero-actions"><a class="btn btn-gold" href="#/builder">Start Building Free →</a><a class="btn btn-dark" href="#/templates">Explore Websites</a></div><div class="trust"><span>✓ AI generation</span><span>✓ Hosting + SSL</span><span>✓ Custom domains</span><span>✓ Cancel anytime</span></div></div>${aiHero()}</section></div>
<section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">WHY VELORA</span><h2>From idea to live site.</h2></div><p class="muted">One workspace for creation, hosting and growth.</p></div><div class="cards">
${feature("✦","AI-first creation","Tell us what you want in plain language. The builder turns it into a polished responsive website.")}
${feature("◈","Premium infrastructure","Fast hosting, SSL, deployment workflows and a clean operational dashboard.")}
${feature("↗","Built to grow","Connect your domain, watch analytics and upgrade your site as your business grows.")}
</div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">CURATED STARTING POINTS</span><h2>Premium templates.</h2></div><a class="btn btn-outline" href="#/templates">View all →</a></div>${templateGrid(templates.slice(0,4))}</div></section>
<section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">SIMPLE PRICING</span><h2>Rent instead of rebuilding.</h2></div><a class="btn btn-outline" href="#/pricing">Compare plans →</a></div>${pricingCards()}</div></section>`}

function aiHero(){return `<div class="hero-art"><div class="glow"></div><div class="ai-card"><div class="windowbar"><i class="dot"></i><i class="dot"></i><i class="dot"></i><span class="window-title">VELORA AI BUILDER</span></div><div class="prompt"><label>YOUR PROMPT</label><div class="prompt-box">“Create a luxury restaurant website with a black and gold design, online reservations, menu and customer reviews.”</div></div><div class="generate-line"><span class="pulse"></span><span>AI is designing your website…</span><strong style="margin-left:auto;color:#777">86%</strong></div><div class="preview-mini"><div class="mini-nav"></div><div class="mini-hero"><small>MAISON NOIR</small><br><b>Dining, elevated.</b><div class="mini-lines"></div></div><div class="mini-blocks"><i class="mini-block"></i><i class="mini-block"></i><i class="mini-block"></i></div></div></div></div>`}
function feature(icon,title,text){return `<div class="card"><div class="icon">${icon}</div><h3>${title}</h3><p>${text}</p></div>`}
function templateGrid(arr){return `<div class="template-grid">${arr.map((t,i)=>`<div class="template-card"><div class="template-img"><span class="badge">${t[2]}</span></div><div class="template-body"><b>${t[0]}</b><small>${t[1]}</small><a class="btn btn-dark" href="#/website/${i+1}">View Demo</a></div></div>`).join("")}</div>`}

function builder(){return `<div class="container"><div class="page-head"><div><span class="eyebrow">AI BUILDER</span><h1>Build your next website.</h1><p class="muted">Describe a change. Velora updates the live preview.</p></div><div><button class="btn btn-dark" onclick="builderAction('Undo')">↶</button> <button class="btn btn-dark" onclick="builderAction('Redo')">↷</button> <button class="btn btn-gold" onclick="builderAction('Publish')">Publish ↗</button></div></div>
<div class="builder"><div class="builder-panel"><div class="panel-top"><strong>AI ASSISTANT</strong><span class="pill">GPT-ready</span></div><div class="chat"><div class="messages" id="messages"><div class="msg ai">Tell me what you want to build. I can create pages, sections, copy, layouts and responsive states.</div><div class="msg user">Make the hero section more premium.</div><div class="msg ai">I'll refine the typography, spacing and visual hierarchy while keeping the black-and-gold system consistent.</div></div><div class="chat-form"><textarea id="chatInput" class="chat-input" placeholder="Ask AI to change anything…"></textarea><div class="chat-actions"><button class="btn btn-gold" onclick="generate()">Generate</button><button class="btn btn-dark" onclick="builderAction('Regenerate')">Regenerate</button></div></div></div></div>
<div class="preview-panel"><div class="preview-toolbar"><strong style="font-size:11px">LIVE PREVIEW</strong><div class="device-toggle"><button class="active">Desktop</button><button>Tablet</button><button>Mobile</button></div><button class="btn btn-dark" onclick="toast('Preview opened in a new tab (demo)')">↗</button></div><div class="site-frame"><div class="site-nav"><b>MAISON NOIR</b><span>Menu &nbsp; About &nbsp; Reservations</span></div><div class="site-hero"><small>MODERN FINE DINING</small><h2>Dining, elevated.</h2><p>A refined restaurant experience built around seasonal ingredients, intimate design and memorable evenings.</p><span class="site-btn">Reserve a table</span></div><div class="site-section"><h3>Designed for the experience.</h3><p style="color:#666;line-height:1.6">Every detail is crafted to make the journey from discovery to reservation feel effortless.</p><div class="site-grid"><i class="site-box"></i><i class="site-box"></i><i class="site-box"></i></div></div><div class="site-section"><h3>Guest notes</h3><p style="color:#666">“Beautiful atmosphere, thoughtful menu and exceptional service.”</p></div></div><div class="logs" id="buildLogs"><div class="success">✓ Build successful · 1.8s</div><div>✓ Responsive checks passed</div><div>✓ Assets optimized</div></div></div>
<div class="builder-panel"><div class="panel-top"><strong>PROJECT</strong></div><div class="files"><div class="eyebrow" style="margin:8px 7px">FILES</div>${["/app/page.tsx","/app/about/page.tsx","/components/Navbar.tsx","/components/Hero.tsx","/public/hero.webp","/styles/globals.css","package.json"].map((x,i)=>`<div class="file ${i===0?"active":""}">▱ ${x}</div>`).join("")}<div class="eyebrow" style="margin:18px 7px 8px">DESIGN</div><div class="setting"><label>ACCENT</label><div class="swatches"><i class="swatch" style="background:#e9bd55"></i><i class="swatch" style="background:#7398d8"></i><i class="swatch" style="background:#b77ad9"></i><i class="swatch" style="background:#71b98b"></i></div></div><div class="setting"><label>RADIUS</label><span class="pill">12px · Premium</span></div></div></div></div></div>`}

function generate(){const input=document.querySelector("#chatInput");const text=input?.value.trim()||"Make the website more premium.";const msgs=document.querySelector("#messages");if(msgs){msgs.insertAdjacentHTML("beforeend",`<div class="msg user">${escapeHtml(text)}</div><div class="msg ai" id="thinking">Analyzing request…</div>`);msgs.scrollTop=msgs.scrollHeight}input.value="";const logs=document.querySelector("#buildLogs");setTimeout(()=>{document.querySelector("#thinking")?.remove();msgs?.insertAdjacentHTML("beforeend",`<div class="msg ai">Done. I updated the design system, refined spacing and regenerated the affected components.</div>`);logs.innerHTML='<div class="success">✓ AI changes applied</div><div class="success">✓ Build successful</div><div>✓ Responsive checks passed</div>';toast("Website updated by AI");},1200)}
function builderAction(x){toast(x+" action completed")}
function escapeHtml(s){return s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}

function templatesPage(){return `<div class="container page"><div class="page-head"><div><span class="eyebrow">TEMPLATE MARKETPLACE</span><h1>Start with something great.</h1><p class="muted">Premium foundations you can customize with AI.</p></div></div><div class="cards" style="grid-template-columns:repeat(5,1fr);margin-bottom:22px">${["All","Restaurant","Salon","Gym","Real Estate"].map(x=>`<button class="btn btn-dark" onclick="toast('${x} selected')">${x}</button>`).join("")}</div>${templateGrid(templates)}</div>`}

function pricing(){return `<div class="container page"><div class="section-head"><div><span class="eyebrow">PRICING</span><h1>Rent the right website.</h1><p class="muted">Monthly or yearly. No lock-in.</p></div><div class="pill">YEARLY · SAVE 20%</div></div>${pricingCards()}</div>`}
function pricingCards(){return `<div class="pricing">${price("Starter","₹999","1 website","AI generation","Hosting + SSL","Basic analytics")}<div class="card price-card featured"><span class="badge">MOST POPULAR</span><span class="eyebrow">BUSINESS</span><div class="price">₹1,999 <span>/ month</span></div><p class="muted">For growing businesses that need a stronger digital presence.</p><ul class="feature-list"><li>1 premium website</li><li>Advanced AI editing</li><li>Custom domain</li><li>Analytics</li><li>Priority support</li></ul><a class="btn btn-gold" href="#/signup">Start Business</a></div>${price("Premium","₹3,999","Premium website","Advanced AI","Custom domain","Advanced analytics","Business features","Priority support")}</div>`}
function price(name,cost,...features){return `<div class="card price-card"><span class="eyebrow">${name.toUpperCase()}</span><div class="price">${cost} <span>/ month</span></div><p class="muted">A simple managed website subscription.</p><ul class="feature-list">${features.map(f=>`<li>${f}</li>`).join("")}</ul><a class="btn btn-dark" href="#/signup">Choose ${name}</a></div>`}

function how(){return `<div class="container page"><div class="section-head"><div><span class="eyebrow">HOW IT WORKS</span><h1>One prompt. One polished website.</h1><p class="muted">A production-minded workflow, simplified for the customer.</p></div></div><div class="cards">${feature("01","Describe","Tell Velora what your business needs and the visual direction you like.")}${feature("02","Generate","The AI agent plans pages, creates components, checks the build and prepares a preview.")}${feature("03","Refine","Chat with the site. Change colors, sections, copy, layouts or functionality.")}${feature("04","Publish","Choose a rental plan, publish the site and connect your custom domain.")}${feature("05","Measure","Use analytics and the dashboard to understand how the website performs.")}${feature("06","Grow","Upgrade your plan or iterate with AI whenever your business evolves.")}</div></div>`}

function auth(title,sub){return `<div class="container"><div class="form-page"><span class="eyebrow">VELORA ACCOUNT</span><h1>${title}</h1><p class="muted">${sub}</p><div class="form">${title.includes("Reset")?`<div class="field"><label>EMAIL</label><input type="email" placeholder="you@business.com"></div><button class="btn btn-gold" onclick="toast('Reset link sent')">Send Reset Link</button>`:`<div class="field"><label>EMAIL</label><input type="email" placeholder="you@business.com"></div><div class="field"><label>PASSWORD</label><input type="password" placeholder="••••••••"></div><button class="btn btn-gold" onclick="toast('Demo authentication successful')">${title.includes("Create")?"Create Account":"Log In"}</button><div class="divider">OR</div><button class="btn btn-dark" onclick="toast('Google sign-in demo')">Continue with Google</button>`}</div><p class="muted" style="text-align:center;margin-top:15px;font-size:11px">${title.includes("Create")?'Already have an account? <a href="#/login" style="color:#ddd">Log in</a>':'New to Velora? <a href="#/signup" style="color:#ddd">Create an account</a>'}</p></div></div>`}

function dashNav(label,icon,route,active){return `<a class="dash-nav ${active===label?"active":""}" href="#/dashboard${route}">${icon}<span>${label}</span></a>`}
function dashboard(active){return `<div class="dashboard"><aside class="dash-side"><div class="nav-title">WORKSPACE</div>${dashNav("Overview","⌂","",active)}${dashNav("My Websites","◈","/websites",active)}${dashNav("AI Builder","✦","",active)}${dashNav("Templates","▦","",active)}${dashNav("Domains","◎","/domains",active)}${dashNav("Analytics","↗","/analytics",active)}${dashNav("Billing","◫","/billing",active)}${dashNav("Settings","⚙","/settings",active)}<div style="margin-top:35px;padding:10px;color:#555;font-size:9px">DEMO WORKSPACE<br><b style="color:#aaa">raj@business.com</b></div></aside><section class="dash-main">${dashboardContent(active)}</section></div>`}
function dashboardContent(active){if(active==="Domains")return domains();if(active==="Billing")return billing();if(active==="Analytics")return analytics();if(active==="Settings")return settings();return `<div class="page-head"><div><span class="eyebrow">CUSTOMER DASHBOARD</span><h1>${active==="My Websites"?"My Websites":"Good evening, Raj."}</h1><p class="muted">Everything you need to manage your digital presence.</p></div><a class="btn btn-gold" href="#/builder">+ New Website</a></div><div class="dash-stats"><div class="dash-stat"><small>ACTIVE WEBSITES</small><b>4</b><span class="muted">All live</span></div><div class="dash-stat"><small>MONTHLY SPEND</small><b>₹7,996</b><span class="muted">Next bill Sep 01</span></div><div class="dash-stat"><small>VISITORS</small><b>32.9K</b><span class="muted">+18.4%</span></div><div class="dash-stat"><small>AI CREDITS</small><b>842</b><span class="muted">of 1,000</span></div></div><div class="dash-grid"><div class="card"><div class="section-head" style="margin-bottom:12px"><h3>Active websites</h3><a class="muted" href="#/dashboard/websites">View all →</a></div><div class="project-list">${state.projects.map(p=>`<div class="project"><div class="project-thumb"></div><div class="project-info"><b>${p.name}</b><small>${p.domain} · ${p.plan}</small></div><span class="live">● LIVE</span><button class="btn btn-dark" onclick="toast('Opening ${p.name}')">Manage</button></div>`).join("")}</div></div><div class="card"><span class="eyebrow">TRAFFIC</span><h3>Visitors this month</h3><div class="chart">${[40,55,45,72,62,82,70,94,76,100].map((n,i)=>`<div class="bar-wrap"><div class="bar" style="height:${n}%"></div><div class="bar-label">${["M","T","W","T","F","S","S","","",""][i]}</div></div>`).join("")}</div></div></div>`}
function domains(){return `<div class="page-head"><div><span class="eyebrow">DOMAINS</span><h1>Connect your domain.</h1><p class="muted">Verify DNS, SSL and publishing status.</p></div><button class="btn btn-gold" onclick="toast('Domain form opened')">+ Add Domain</button></div><div class="card"><div class="domain-row"><div><b>mybusiness.com</b><small class="muted">Urban Fitness</small></div><span class="status">✓ CONNECTED · SSL ACTIVE</span></div><div class="domain-row"><div><b>velora-demo.com</b><small class="muted">Velora Restaurant</small></div><span class="status">✓ CONNECTED · SSL ACTIVE</span></div></div>`}
function billing(){return `<div class="page-head"><div><span class="eyebrow">BILLING</span><h1>Subscription & payments.</h1><p class="muted">Manage plans, invoices and payment methods.</p></div><button class="btn btn-gold" onclick="toast('Plan selector opened')">Change plan</button></div><div class="card"><span class="eyebrow">CURRENT PLAN</span><h2>Business · ₹1,999/month</h2><p class="muted">Next billing date: September 01, 2026</p><div class="billing-row"><span>•••• 4242 · Visa</span><button class="btn btn-dark">Update</button></div><div class="billing-row"><span>INV-2026-08 · ₹7,996</span><span class="pill">PAID</span></div></div>`}
function analytics(){return `<div class="page-head"><div><span class="eyebrow">ANALYTICS</span><h1>Performance at a glance.</h1><p class="muted">Traffic across your active websites.</p></div></div><div class="dash-stats"><div class="dash-stat"><small>VISITORS</small><b>32,891</b><span class="muted">+18.4%</span></div><div class="dash-stat"><small>PAGE VIEWS</small><b>71,203</b><span class="muted">+12.8%</span></div><div class="dash-stat"><small>CONVERSION</small><b>4.8%</b><span class="muted">+0.9%</span></div><div class="dash-stat"><small>TOP SITE</small><b>Urban</b><span class="muted">12.4K visitors</span></div></div><div class="card" style="margin-top:14px"><span class="eyebrow">30 DAY TREND</span><h3>Website traffic</h3><div class="chart" style="height:280px">${[25,31,35,29,45,51,49,63,58,70,66,82,77,91].map(n=>`<div class="bar-wrap"><div class="bar" style="height:${n}%"></div></div>`).join("")}</div></div>`}
function settings(){return `<div class="page-head"><div><span class="eyebrow">SETTINGS</span><h1>Workspace settings.</h1><p class="muted">Account, notifications and preferences.</p></div></div><div class="card"><div class="field"><label>WORKSPACE NAME</label><input value="Raj's Business Studio"></div><div class="field"><label>EMAIL</label><input value="raj@business.com"></div><button class="btn btn-gold" onclick="toast('Settings saved')">Save changes</button></div>`}

function websiteDetail(){return `<div class="container page"><div class="page-head"><div><span class="eyebrow">PREMIUM WEBSITE</span><h1>Maison Noir</h1><p class="muted">Luxury restaurant · Responsive · AI editable</p></div><a class="btn btn-gold" href="#/signup">Rent This Website →</a></div><div class="card" style="padding:12px"><div class="site-frame" style="height:600px;margin:0"><div class="site-nav"><b>MAISON NOIR</b><span>Menu &nbsp; About &nbsp; Reservations</span></div><div class="site-hero"><small>MODERN FINE DINING</small><h2>Dining, elevated.</h2><p>A refined restaurant experience built around seasonal ingredients and memorable evenings.</p><span class="site-btn">Reserve a table</span></div><div class="site-section"><h3>Designed for the experience.</h3><div class="site-grid"><i class="site-box"></i><i class="site-box"></i><i class="site-box"></i></div></div></div></div></div>`}

function admin(){return `<div class="container page"><div class="page-head"><div><span class="eyebrow">ADMIN CONSOLE</span><h1>Platform overview.</h1><p class="muted">Operational metrics for Velora.</p></div><span class="pill">SYSTEM HEALTH · 99.98%</span></div><div class="dash-stats"><div class="dash-stat"><small>TOTAL USERS</small><b>12,842</b></div><div class="dash-stat"><small>ACTIVE WEBSITES</small><b>8,421</b></div><div class="dash-stat"><small>MRR</small><b>₹1.84Cr</b></div><div class="dash-stat"><small>AI GENERATIONS</small><b>384K</b></div></div><div class="dash-grid"><div class="card"><span class="eyebrow">REVENUE</span><h3>Monthly recurring revenue</h3><div class="chart">${[35,43,47,52,58,61,69,74,82,89].map(n=>`<div class="bar-wrap"><div class="bar" style="height:${n}%"></div></div>`).join("")}</div></div><div class="card"><span class="eyebrow">SYSTEM LOGS</span><div class="logs" style="border:0;max-height:none"><div class="success">✓ deploy-worker healthy</div><div class="success">✓ ai-gateway healthy</div><div>• 42 builds running</div><div>• 3 domain verifications</div><div>• 0 payment webhook failures</div></div></div></div>`}

function bind(){document.querySelector("#menuBtn")?.addEventListener("click",()=>document.querySelector("#mobileNav").classList.toggle("open"));document.querySelectorAll(".device-toggle button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".device-toggle button").forEach(x=>x.classList.remove("active"));b.classList.add("active");toast(b.textContent+" preview")})}
window.addEventListener("hashchange",app);app();